layout_spectrum: 0.8893725241068751
typography_spectrum: 0.2941307171713561
color:
  brandStrength: 0.38005106593482196
  lightness: 0.3943110886029899
  saturation: 0.37626492022536695
  rhythmicContrast: 0.9179920977912843
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
name: Multilena.grid
navigation:
  - name: Lena interactive designer
    url: 'http://multilena.com'
    type: external
title: Lena.Interactive
description: UI & UX Services
